### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by ai** [gikmx/postcss-queries#1]
Really nice idea! But we could make it smarter.

What do you think if you will add JS API:

```
postcss([
  require('postcss-queries')
  require('postcss-custom-media')
])
```

And this plugin will do:
1. Check that build process contains `postcss-custom-media` and add warning if it was missed.
2. Check what media queries is really used by browsers and auto-import any necessary ones
3. Also it will allow to miss `postcss-import` plugin.

**Comment by hectormenendez** [comment]
Sorry for taking too long to respond. I've been busy on other projects lately. I will look into this on the weekend. (or if you wan't to make a PR even better)
